/** The renderer receives capabilities, never Node or an unrestricted IPC handle. */
const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('forgeDesktop', Object.freeze({
  chooseProject: () => ipcRenderer.invoke('project:choose'),
  openProject: dir => ipcRenderer.invoke('project:open', dir),
  repairProject: dir => ipcRenderer.invoke('project:repair', dir),
  forgetProject: dir => ipcRenderer.invoke('project:forget', dir),
  createProject: name => ipcRenderer.invoke('project:create', name),
  revealProject: dir => ipcRenderer.invoke('project:reveal', dir),
  listProjects: () => ipcRenderer.invoke('project:list'),
  quit: () => ipcRenderer.invoke('app:quit'),
  assets: () => ipcRenderer.invoke('project:assets'),
  documents: () => ipcRenderer.invoke('project:documents'),
  enginePlan: () => ipcRenderer.invoke('engine:plan'),
  engineUpgrade: (token, approved) => ipcRenderer.invoke('engine:upgrade', token, approved),
  engineBackups: () => ipcRenderer.invoke('engine:backups'),
  engineRestore: id => ipcRenderer.invoke('engine:restore', id),
  settings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: value => ipcRenderer.invoke('settings:save', value),
  updateState: () => ipcRenderer.invoke('update:state'),
  checkUpdate: () => ipcRenderer.invoke('update:check'),
  downloadUpdate: () => ipcRenderer.invoke('update:download'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  onUpdateState: callback => { const listener = (_event, state) => callback(state); ipcRenderer.on('update:state', listener); return () => ipcRenderer.removeListener('update:state', listener); },
  save: (relative, text) => ipcRenderer.invoke('project:save', relative, text),
  importAssets: () => ipcRenderer.invoke('project:import'),
  buildGame: () => ipcRenderer.invoke('project:build'),
  runGame: () => ipcRenderer.invoke('project:run'),
  previewGame: (level, mode, defaults = null) => ipcRenderer.invoke('game:preview', level, mode, defaults),
  stopGame: () => ipcRenderer.invoke('game:stop'),
  readScene: filename => ipcRenderer.invoke('project:scene', filename),
  deleteScene: filename => ipcRenderer.invoke('project:scene-delete', filename),
  onGameState: callback => { const listener = (_event, playing) => callback(playing); ipcRenderer.on('game:state', listener); return () => ipcRenderer.removeListener('game:state', listener); },
  onBuildLog: callback => { const listener = (_event, line) => callback(String(line)); ipcRenderer.on('project:log', listener); return () => ipcRenderer.removeListener('project:log', listener); }
}));
